# Generated by Django 4.2.7 on 2024-07-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_activitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsandevents",
            name="posted_as",
            field=models.CharField(
                choices=[("Новости", "Новости"), ("События", "События")], max_length=10
            ),
        ),
    ]
