# Generated by Django 4.2.7 on 2024-07-01 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_alter_upload_file_alter_uploadvideo_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_course_modification", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[("Бакалавр", "Бакалавр"), ("Магистр", "Магистр")],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[
                    ("Первый", "Первый"),
                    ("Второй", "Второй"),
                    ("Третий", "Третий"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(
                help_text="Допустимые файлы: pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip",
                upload_to="course_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "docx",
                            "doc",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "zip",
                            "rar",
                            "7zip",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="uploadvideo",
            name="video",
            field=models.FileField(
                help_text="Допустимые форматы видео: mp4, mkv, wmv, 3gp, f4v, avi, mp3",
                upload_to="course_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "mkv", "wmv", "3gp", "f4v", "avi", "mp3"]
                    )
                ],
            ),
        ),
    ]
